## Spam Ham classification Project using word2Vec and avgword2Vec
 
     1. Data Preprocessing and cleaning
     2. Train Test Split
     3. Word2Vec model creation  (sentence ---> vector) (preventing data leakage)
     4. Train model

In [1]:
import gensim

from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vc_king = wv['king']

In [3]:
vc_king.shape

(300,)

In [4]:
vc_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [5]:
import pandas as pd

messages = pd.read_csv('sms-spam/spam.csv')

In [6]:
messages = messages[['v1', 'v2']]
messages.columns = ['label', 'message']
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
from nltk.stem import WordNetLemmatizer
import re

lemitizer = WordNetLemmatizer()

In [8]:
corpus = []

for i in range(len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [lemitizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [47]:
## dependent feature
## output features

y = messages[list(map(lambda x : len(x)>0 , corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:, 0].values

In [48]:
y.shape

(5569,)

In [11]:
[[i, j, k] for i, j, k in zip(list(map(len, corpus)), corpus, messages['message']) if i < 1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [12]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
words = []

for sent in corpus:
    sent_token = sent_tokenize(sent)

    for word in sent_token:
        words.append(simple_preprocess(word))

In [15]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [18]:
import gensim

In [19]:
## lets train word2vec

model = gensim.models.Word2Vec(words)

In [20]:
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'ur',
 'will',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'home',
 'don',
 'stop',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'pls',
 'her',
 'please',
 'ha',
 'co',
 'msg',
 'did',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'who',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'clai

In [21]:
model.corpus_count

5569

In [22]:
model.epochs

5

In [23]:
model.wv.similar_by_word('kid')

[('still', 0.9975587129592896),
 ('did', 0.9975263476371765),
 ('one', 0.9974007606506348),
 ('up', 0.9973349571228027),
 ('feel', 0.9973220825195312),
 ('ya', 0.997305691242218),
 ('stay', 0.9972981810569763),
 ('work', 0.9972948431968689),
 ('mind', 0.9972659945487976),
 ('ask', 0.9972600340843201)]

In [24]:
model.wv.similar_by_word('happy')

[('day', 0.9988709092140198),
 ('dear', 0.9987573027610779),
 ('good', 0.9987296462059021),
 ('wa', 0.9987136721611023),
 ('having', 0.9986505508422852),
 ('amp', 0.9986028075218201),
 ('morning', 0.9985606670379639),
 ('all', 0.9985204935073853),
 ('hope', 0.9984903335571289),
 ('wish', 0.99845951795578)]

In [25]:
model.wv['good'].shape

(100,)

In [26]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [27]:
import numpy as np

In [28]:
def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    
    return np.mean(vectors, axis=0)


In [29]:
!pip install tqdm

In [30]:
from tqdm import tqdm

In [31]:
x = []
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 5569/5569 [00:01<00:00, 5362.02it/s]


In [32]:
x

[array([-1.93253696e-01,  2.38394871e-01,  1.80799082e-01,  1.14342578e-01,
         1.21735424e-01, -3.93099964e-01,  2.45393187e-01,  5.75950980e-01,
        -3.24666619e-01, -1.32462353e-01, -1.47960573e-01, -3.63243490e-01,
        -9.85987112e-02,  9.56363529e-02,  1.38505653e-01, -1.36189014e-01,
         1.03530914e-01, -3.19838822e-01,  2.35693827e-02, -5.33927202e-01,
         1.87045470e-01,  3.00262004e-01,  9.73782614e-02, -2.21965075e-01,
        -5.68894744e-02,  6.97657615e-02, -2.14239344e-01, -1.65236995e-01,
        -2.51388043e-01,  5.23128696e-02,  1.91681623e-01,  1.48399221e-02,
         1.61685660e-01, -1.79179281e-01, -4.96741273e-02,  3.62686425e-01,
        -4.98485900e-02, -1.80950254e-01, -1.12813793e-01, -4.39924300e-01,
         7.12954104e-02, -2.22630799e-01, -2.19390571e-01, -4.82632481e-02,
         2.60606945e-01, -4.11601067e-02, -1.27431303e-01, -1.07905529e-01,
         1.70605093e-01,  1.65193275e-01,  1.24370791e-01, -2.47821674e-01,
        -1.4

In [34]:
x[0]

array([-1.93253696e-01,  2.38394871e-01,  1.80799082e-01,  1.14342578e-01,
        1.21735424e-01, -3.93099964e-01,  2.45393187e-01,  5.75950980e-01,
       -3.24666619e-01, -1.32462353e-01, -1.47960573e-01, -3.63243490e-01,
       -9.85987112e-02,  9.56363529e-02,  1.38505653e-01, -1.36189014e-01,
        1.03530914e-01, -3.19838822e-01,  2.35693827e-02, -5.33927202e-01,
        1.87045470e-01,  3.00262004e-01,  9.73782614e-02, -2.21965075e-01,
       -5.68894744e-02,  6.97657615e-02, -2.14239344e-01, -1.65236995e-01,
       -2.51388043e-01,  5.23128696e-02,  1.91681623e-01,  1.48399221e-02,
        1.61685660e-01, -1.79179281e-01, -4.96741273e-02,  3.62686425e-01,
       -4.98485900e-02, -1.80950254e-01, -1.12813793e-01, -4.39924300e-01,
        7.12954104e-02, -2.22630799e-01, -2.19390571e-01, -4.82632481e-02,
        2.60606945e-01, -4.11601067e-02, -1.27431303e-01, -1.07905529e-01,
        1.70605093e-01,  1.65193275e-01,  1.24370791e-01, -2.47821674e-01,
       -1.46293849e-01, -

In [ ]:
x_new = np.array(x)

In [ ]:
x_new.shape

(5569, 100)

In [ ]:
x_new[0]   

array([-0.1938514 ,  0.27079919,  0.18547225,  0.12106271,  0.11985314,
       -0.37333325,  0.22788709,  0.56896746, -0.33086121, -0.12668978,
       -0.16891555, -0.39927992, -0.09730569,  0.08748344,  0.14605561,
       -0.1605656 ,  0.10025535, -0.33073205, -0.01270643, -0.5262183 ,
        0.19090813,  0.27300182,  0.09314258, -0.22966157, -0.06492011,
        0.08356686, -0.18176135, -0.20909804, -0.2768797 ,  0.05044517,
        0.15194681, -0.00934217,  0.15083197, -0.19069925, -0.04347597,
        0.36646375, -0.02696348, -0.16124341, -0.15739699, -0.41792643,
        0.06829914, -0.20506157, -0.21070312, -0.04639171,  0.26438385,
       -0.04371712, -0.1330467 , -0.11734217,  0.17198856,  0.16880777,
        0.13129237, -0.24782628, -0.12937023, -0.02430758, -0.12770055,
        0.1241942 ,  0.09968264,  0.02051656, -0.3633261 ,  0.15879457,
       -0.09739604,  0.07232508,  0.03785594, -0.12169869, -0.32547408,
        0.28664914,  0.16443224,  0.25843239, -0.34500682,  0.25

In [ ]:
x_new.shape

(5569, 100)

In [ ]:
x_new[0].shape

(100,)

In [35]:
x[0].reshape(1, -1)

array([[-1.93253696e-01,  2.38394871e-01,  1.80799082e-01,
         1.14342578e-01,  1.21735424e-01, -3.93099964e-01,
         2.45393187e-01,  5.75950980e-01, -3.24666619e-01,
        -1.32462353e-01, -1.47960573e-01, -3.63243490e-01,
        -9.85987112e-02,  9.56363529e-02,  1.38505653e-01,
        -1.36189014e-01,  1.03530914e-01, -3.19838822e-01,
         2.35693827e-02, -5.33927202e-01,  1.87045470e-01,
         3.00262004e-01,  9.73782614e-02, -2.21965075e-01,
        -5.68894744e-02,  6.97657615e-02, -2.14239344e-01,
        -1.65236995e-01, -2.51388043e-01,  5.23128696e-02,
         1.91681623e-01,  1.48399221e-02,  1.61685660e-01,
        -1.79179281e-01, -4.96741273e-02,  3.62686425e-01,
        -4.98485900e-02, -1.80950254e-01, -1.12813793e-01,
        -4.39924300e-01,  7.12954104e-02, -2.22630799e-01,
        -2.19390571e-01, -4.82632481e-02,  2.60606945e-01,
        -4.11601067e-02, -1.27431303e-01, -1.07905529e-01,
         1.70605093e-01,  1.65193275e-01,  1.24370791e-0

In [36]:
x[0].reshape(1, -1).shape

(1, 100)

In [39]:
### final independent feature
df = pd.DataFrame()

for i in range(len(x)):
    temp = pd.DataFrame([x[i]])   # or x[i].reshape(1, -1)
    df = pd.concat([df, temp], ignore_index=True)

In [ ]:
## faster from above code...
df = pd.DataFrame(x)

In [42]:
df.shape

(5569, 100)

In [44]:
df.head()

0         1         2         3         4         5         6   \
0 -0.193254  0.238395  0.180799  0.114343  0.121735 -0.393100  0.245393   
1 -0.173992  0.204427  0.155436  0.090888  0.110308 -0.337134  0.201658   
2 -0.191628  0.243637  0.194679  0.132820  0.125280 -0.430197  0.235293   
3 -0.269285  0.326904  0.243955  0.150316  0.166884 -0.532166  0.335283   
4 -0.232965  0.269262  0.210007  0.122124  0.149013 -0.449813  0.280068   

         7         8         9   ...        90        91        92        93  \
0  0.575951 -0.324667 -0.132462  ...  0.290227  0.209205  0.119553  0.137827   
1  0.493106 -0.279794 -0.109818  ...  0.252463  0.170886  0.097395  0.118058   
2  0.572420 -0.339051 -0.127954  ...  0.314999  0.211050  0.112818  0.140507   
3  0.782568 -0.450558 -0.186414  ...  0.388157  0.268986  0.149907  0.194882   
4  0.660167 -0.373499 -0.168018  ...  0.330514  0.223400  0.131624  0.169352   

         94        95        96        97        98        99  
0  0.463678  0.267720  0.058691 -0.252191  0.163221 -0.032894  
1  0.393183  0.231758  0.047138 -0.226092  0.136901 -0.031041  
2  0.469453  0.261216  0.050150 -0.277539  0.167768 -0.010866  
3  0.624517  0.363844  0.079601 -0.357075  0.215735 -0.040779  
4  0.528877  0.312853  0.062703 -0.301146  0.182092 -0.036388  

[5 rows x 100 columns]

In [45]:
df.tail()

0         1         2         3         4         5         6   \
5564 -0.219551  0.284403  0.230706  0.146798  0.146437 -0.475450  0.286497   
5565 -0.242674  0.285700  0.223578  0.139441  0.159711 -0.479411  0.293403   
5566 -0.258800  0.316879  0.237786  0.140504  0.155309 -0.524992  0.324514   
5567 -0.234714  0.284702  0.221859  0.135308  0.152886 -0.479754  0.289298   
5568 -0.257973  0.302334  0.233003  0.144475  0.165644 -0.513057  0.307402   

            7         8         9   ...        90        91        92  \
5564  0.672657 -0.389049 -0.152389  ...  0.354616  0.249715  0.147210   
5565  0.691776 -0.399940 -0.159463  ...  0.361240  0.237340  0.131368   
5566  0.766260 -0.428106 -0.185384  ...  0.376623  0.279859  0.161729   
5567  0.688287 -0.390896 -0.163976  ...  0.350677  0.246691  0.144789   
5568  0.740247 -0.429160 -0.181830  ...  0.376589  0.256766  0.153373   

            93        94        95        96        97        98        99  
5564  0.159571  0.546688  0.311245  0.065692 -0.311461  0.202829 -0.021353  
5565  0.166050  0.560885  0.319595  0.059184 -0.318896  0.190002 -0.033475  
5566  0.189437  0.619097  0.363030  0.085972 -0.324502  0.220534 -0.045074  
5567  0.172612  0.558962  0.327283  0.071154 -0.305125  0.193481 -0.038227  
5568  0.179097  0.589819  0.342869  0.077867 -0.329421  0.209723 -0.039436  

[5 rows x 100 columns]

In [54]:
df['output'] = y

In [55]:
df.head()

0         1         2         3         4         5         6  \
0 -0.193254  0.238395  0.180799  0.114343  0.121735 -0.393100  0.245393   
1 -0.173992  0.204427  0.155436  0.090888  0.110308 -0.337134  0.201658   
2 -0.191628  0.243637  0.194679  0.132820  0.125280 -0.430197  0.235293   
3 -0.269285  0.326904  0.243955  0.150316  0.166884 -0.532166  0.335283   
4 -0.232965  0.269262  0.210007  0.122124  0.149013 -0.449813  0.280068   

          7         8         9  ...        91        92        93        94  \
0  0.575951 -0.324667 -0.132462  ...  0.209205  0.119553  0.137827  0.463678   
1  0.493106 -0.279794 -0.109818  ...  0.170886  0.097395  0.118058  0.393183   
2  0.572420 -0.339051 -0.127954  ...  0.211050  0.112818  0.140507  0.469453   
3  0.782568 -0.450558 -0.186414  ...  0.268986  0.149907  0.194882  0.624517   
4  0.660167 -0.373499 -0.168018  ...  0.223400  0.131624  0.169352  0.528877   

         95        96        97        98        99  output  
0  0.267720  0.058691 -0.252191  0.163221 -0.032894    True  
1  0.231758  0.047138 -0.226092  0.136901 -0.031041    True  
2  0.261216  0.050150 -0.277539  0.167768 -0.010866   False  
3  0.363844  0.079601 -0.357075  0.215735 -0.040779    True  
4  0.312853  0.062703 -0.301146  0.182092 -0.036388    True  

[5 rows x 101 columns]

In [57]:
df.dropna(inplace=True)

In [58]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
output    0
Length: 101, dtype: int64

In [ ]:
## Independent feature
x = df

In [59]:
y = df['output']

In [49]:
x.shape

(5569, 100)

In [50]:
## train test split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [60]:
x_train.head()

0         1         2         3         4         5         6   \
3529 -0.186265  0.294597  0.229951  0.150179  0.110867 -0.484745  0.319431   
1775 -0.173959  0.247186  0.216741  0.167284  0.131229 -0.443146  0.231641   
1638 -0.223210  0.269858  0.217686  0.143900  0.148631 -0.481715  0.268579   
1985 -0.033175  0.041156  0.021977  0.023956  0.029101 -0.072549  0.042898   
1330 -0.194617  0.248113  0.179906  0.112883  0.121154 -0.401076  0.243758   

            7         8         9   ...        90        91        92  \
3529  0.713440 -0.392167 -0.150976  ...  0.333004  0.297668  0.198970   
1775  0.583754 -0.340584 -0.110718  ...  0.361635  0.223457  0.117261   
1638  0.649902 -0.382256 -0.150974  ...  0.349306  0.229377  0.124252   
1985  0.099209 -0.058352 -0.030665  ...  0.053073  0.024824  0.024623   
1330  0.600457 -0.326316 -0.140655  ...  0.307017  0.208095  0.116361   

            93        94        95        96        97        98        99  
3529  0.179152  0.590519  0.356488  0.116438 -0.244585  0.205070 -0.075204  
1775  0.122468  0.479177  0.251018  0.019818 -0.312643  0.164399  0.005720  
1638  0.159299  0.529548  0.297132  0.057194 -0.313707  0.185722 -0.017335  
1985  0.017091  0.074238  0.053127  0.003273 -0.044356  0.025064  0.001786  
1330  0.138222  0.481197  0.276562  0.056325 -0.259596  0.153534 -0.036222  

[5 rows x 100 columns]

In [61]:
y_train

array([ True, False, False, ...,  True,  True,  True], shape=(4455,))

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
classifier = RandomForestClassifier()

In [64]:
classifier.fit(x_train, y_train)

RandomForestClassifier()

In [65]:
y_pred = classifier.predict(x_test)

In [66]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [67]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9622980251346499
[[124  23]
 [ 19 948]]
              precision    recall  f1-score   support

       False       0.87      0.84      0.86       147
        True       0.98      0.98      0.98       967

    accuracy                           0.96      1114
   macro avg       0.92      0.91      0.92      1114
weighted avg       0.96      0.96      0.96      1114

