## Word2Vec Implementation

In [1]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   --- ------------------------------------ 2.1/24.4 MB 11.8 MB/s eta 0:00:02
   ------- -------------------------------- 4.5/24.4 MB 11.2 MB/s eta 0:00:02
   ---------- ----------------------------- 6.3/24.4 MB 10.2 MB/s eta 0:00:02
   ------------- -------------------------- 8.1/24.4 MB 9.7 MB/s eta 0:00:02
   --------------- ------------------------ 9.4/24.4 MB 9.3 MB/s eta 0:00:02
   ----------------- ---------------------- 10.5/24.4 MB 8.3 MB/s eta 0:00:02
   -------------------- ------------------- 12.6/24.4 MB 8.4 MB/s eta 0:00:02
   ----------------------- ---------------- 14.2/24.4 MB 8.4 MB/s eta 0:00:02
   --------------------------- ------------ 16.5/24.4 MB 8.5 MB/s eta 0:00:01
   ------------------------------ --------- 18.6/24.4 MB 8.6 MB/s eta 0:00:01
   --------------------------------- ------ 20.7/24.4 MB 8.8 MB/s eta 0:00:01
   ---------------------------------- ----- 21.0/24.4 MB 8.8 MB/s eta 0:00

In [2]:
import gensim
from gensim.models import word2vec, KeyedVectors

In [4]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [8]:
vec_king.shape

(300,)

In [9]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [10]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [11]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [12]:
wv.most_similar('sad')

[('saddening', 0.7273085713386536),
 ('Sad', 0.6610826849937439),
 ('saddened', 0.6604382395744324),
 ('heartbreaking', 0.6573508381843567),
 ('disheartening', 0.6507317423820496),
 ('Meny_Friedman', 0.6487058401107788),
 ('parishioner_Pat_Patello', 0.6475860476493835),
 ('saddens_me', 0.6407119035720825),
 ('distressing', 0.6399092674255371),
 ('reminders_bobbing', 0.6357713341712952)]

In [22]:
wv.most_similar('mother')

[('daughter', 0.8706234097480774),
 ('grandmother', 0.8442240953445435),
 ('aunt', 0.843592643737793),
 ('niece', 0.807008683681488),
 ('father', 0.7901482582092285),
 ('son', 0.7683205604553223),
 ('sister', 0.7633354067802429),
 ('wife', 0.7550681233406067),
 ('stepmother', 0.7531880140304565),
 ('granddaughter', 0.7470966577529907)]

In [23]:
wv.similarity('happy', 'sad')

np.float32(0.5354614)

In [ ]:
wv.similarity('sports', 'cricket')

np.float32(0.40087253)

In [34]:
wv.similarity('goal', 'goalkeeper')

np.float32(0.38828698)

In [37]:
wv.similarity('love', 'cheat')

np.float32(0.22706395)

In [40]:
vec = wv['king']-wv['men']+wv['women']

In [41]:
vec

array([ 3.41796875e-02,  2.68554688e-02, -5.34057617e-02,  2.45452881e-01,
       -3.24707031e-02, -7.42187500e-02,  2.08496094e-01, -2.80517578e-01,
        2.92968750e-03,  2.65136719e-01, -3.33251953e-01, -2.96875000e-01,
       -1.06689453e-01,  3.46679688e-02, -8.41064453e-02, -1.28906250e-01,
       -4.63867188e-02,  1.69677734e-02,  3.09143066e-02,  1.46484375e-01,
        1.92382812e-01,  1.70043945e-01,  3.56445312e-02,  6.25000000e-02,
       -1.92871094e-02, -1.30859375e-01, -2.73437500e-01, -1.53808594e-02,
        1.57470703e-01, -1.97875977e-01, -7.56988525e-02, -3.97949219e-02,
       -4.77066040e-02,  2.44873047e-01, -3.29589844e-01,  1.46484375e-03,
        1.78222656e-02,  5.37109375e-02,  9.08203125e-02,  7.91015625e-02,
        8.27941895e-02, -1.40441895e-01,  1.61132812e-01,  1.90917969e-01,
        2.00561523e-01,  1.07421875e-02, -1.35498047e-01,  1.25000000e-01,
        4.39453125e-02,  3.24096680e-02, -5.27343750e-02, -4.88281250e-04,
       -3.24516296e-01,  

In [42]:
wv.most_similar([vec])

[('king', 0.8527070879936218),
 ('queen', 0.6743921637535095),
 ('monarch', 0.6191632151603699),
 ('kings', 0.5753854513168335),
 ('crown_prince', 0.562209963798523),
 ('princess', 0.543317437171936),
 ('prince', 0.5246985554695129),
 ('sultan', 0.5236638784408569),
 ('ruler', 0.5165805220603943),
 ('monarchy', 0.5113592147827148)]